In [1]:
import requests
import csv
import pandas as pd

In [2]:
# Get all teams and save to pandas dataframe
teams = requests.get('https://api.igem.org/v1/teams').json()
teams_df = pd.DataFrame(teams)
teams_df

,id,name,region,country,schools,track,kind,section,status,year,isRemote
0,4442,McMaster_Canada,north-america,Canada,"McMaster University\r\nHamilton, Ontario, Cana...",Diagnostics,collegiate,overgrad,Accepted,2022,False
1,1040,Osaka,asia,Japan,"Osaka University, Toyonaka, Osaka 560-0043, Ja...",Information Processing,collegiate,undergrad,Accepted,2013,None
2,4887,Shanghai-BioX,asia,China,Shanghai Guanghua Cambridge International Scho...,High School,commercial,high_school,Accepted,2023,False
3,4470,SUSTech_Shenzhen_HCL,asia,China,"Southern University of Science and Technology,...",Food & Nutrition,collegiate,undergrad,Withdrawn,2022,None
4,4843,TSB-Center,asia,China,"Hefei No.8 Senior High School,Hefei\r\nNO.1 Mi...",High School,commercial,high_school,Accepted,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
3133,4259,Leiden,europe,Netherlands,"Leiden University, The Netherlands",Manufacturing,collegiate,overgrad,Accepted,2022,False
3134,4433,Linkoping_Sweden,europe,Sweden,Linkoping University,Diagnostics,collegiate,overgrad,Accepted,2022,False
3135,4185,MSP-Maastricht,europe,Netherlands,"Maastricht Science Programme, Maastricht Unive...",Environment,collegiate,undergrad,Accepted,2022,False
3136,4374,Navarra_BG,europe,Spain,"Planetario de Pamplona \r\nPamplona, Navarra, ...",High School,commercial,high_school,Accepted,2022,False
3137,4719,Vilnius-Lithuania,europe,Lithuania,"\t\r\nVilnius University\r\nVilnius, Lithuania...",Biomanufacturing,collegiate,undergrad,Accepted,2023,False

In [3]:
data = requests.get(f'https://api.igem.org/v1/teams/{id}/artifacts').json()[0]

title = data.get('metadata').get('title')
title

for i in range(len(teams_df)):
    row = teams_df.iloc[i]
    try:
        data = requests.get(f'https://api.igem.org/v1/teams/{row[i]}/artifacts').json()[0]
        metadata = data.get('metadata')
    
        teams_df.loc[i]['title'] = metadata.get('title')
        teams_df.loc[i]['abstract'] = metadata.get('abstract')

    except:
        continue
    


def update_with_artifacts(row):
    data = requests.get(f'https://api.igem.org/v1/teams/{id}/artifacts').json()[0]

KeyError: 0

In [11]:
data = requests.get(f'https://api.igem.org/v1/teams/4058/artifacts').json()
data.get['metadata']

AttributeError: 'list' object has no attribute 'get'

In [62]:
def update_artifacts(row):
    try:
        data = requests.get(f'https://api.igem.org/v1/teams/{4058}/artifacts').json()[0]
        metadata = data.get('metadata')

        # todo: also download video links, if available
        row['title'] = metadata.get('title')
        row['abstract'] = metadata.get('abstract')
        print(row['abstract'])
    except:
        pass

teams_df.append("title")
teams_df.apply(update_artifacts, axis=0, inplace=True)

/var/folders/mt/h27yrsld5nd24dfkjmqx7tzm0000gn/T/ipykernel_45141/2713646485.py:13: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  teams_df.append("title")

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid

In [46]:
teams_df

,id,name,region,country,schools,track,kind,section,status,year,isRemote
0,4442,McMaster_Canada,north-america,Canada,"McMaster University\r\nHamilton, Ontario, Cana...",Diagnostics,collegiate,overgrad,Accepted,2022,False
1,1040,Osaka,asia,Japan,"Osaka University, Toyonaka, Osaka 560-0043, Ja...",Information Processing,collegiate,undergrad,Accepted,2013,None
2,4887,Shanghai-BioX,asia,China,Shanghai Guanghua Cambridge International Scho...,High School,commercial,high_school,Accepted,2023,False
3,4470,SUSTech_Shenzhen_HCL,asia,China,"Southern University of Science and Technology,...",Food & Nutrition,collegiate,undergrad,Withdrawn,2022,None
4,4843,TSB-Center,asia,China,"Hefei No.8 Senior High School,Hefei\r\nNO.1 Mi...",High School,commercial,high_school,Accepted,2023,False
...,...,...,...,...,...,...,...,...,...,...,...
3133,4259,Leiden,europe,Netherlands,"Leiden University, The Netherlands",Manufacturing,collegiate,overgrad,Accepted,2022,False
3134,4433,Linkoping_Sweden,europe,Sweden,Linkoping University,Diagnostics,collegiate,overgrad,Accepted,2022,False
3135,4185,MSP-Maastricht,europe,Netherlands,"Maastricht Science Programme, Maastricht Unive...",Environment,collegiate,undergrad,Accepted,2022,False
3136,4374,Navarra_BG,europe,Spain,"Planetario de Pamplona \r\nPamplona, Navarra, ...",High School,commercial,high_school,Accepted,2022,False
3137,4719,Vilnius-Lithuania,europe,Lithuania,"\t\r\nVilnius University\r\nVilnius, Lithuania...",Biomanufacturing,collegiate,undergrad,Accepted,2023,False